### ISSUE TITLE
Might be error from UploadThing or Editorjs

### ISSUE THREAD

**Issue by Nith567** [joschan21/breadit#15]
When i am trying to upload an image or post a link,  its comes up and says :"Couldn’t upload image. Please try another."(for an image)

**Comment by Avijit-Sarkar** [comment]
same problem started to happen

**Comment by joschan21** [comment]
That's not good, might be something UploadThing or EditorJS have changed under the hood

**Comment by SaiSawant1** [comment]
I have just finished the whole video and not getting the error you should reevaluate your code.

**Comment by ryanyogan** [comment]
Either downgrade `upload-thing` to version `4.x`  
`npm install uploadthing@4.x`

Or use the latest documentation as things changed in version `5.0.0`

**Comment by krsnamara** [comment]
Yes I am getting this same issue. Will look into the documentation or downgrade as you have suggested

**Comment by krsnamara** [comment]
Looking at the error message I opened up an internal file and found that uploadthing is just S3 under the hood. Going to get back to it tomorrow and add either S3 or supabase as the image storage function and toss uploadthing.

```
Image Tool: uploading failed because of TypeError: Cannot read properties of undefined (reading 'map')
    at uploadFilesInternal (index.js:168:27)
    at eval (index.js:234:9)
    at Object.uploadByFile (Editor.tsx:72:50)
    at eval `(bundle.js:10:35524)
```
```
// Get presigned URL for S3 upload
    const s3ConnectionRes = await reportEventToUT("upload", {
        input: "input"in opts ? opts.input : null,
        files: opts.files.map((f)=>({
            name: f.name,
            size: f.size,
            type: f.type
        }))
    });    
```
